defmodule PhoenixPaperWebsiteWeb.ThemePicker do
  @moduledoc """
  This showcase site's own live theme picker (`theme_picker/1`), not part of
  PhoenixPaper itself but built from its components: a `pp_icon_button`
  opens a modal `pp_side_sheet` (scrim, Escape and focus trapping come with
  it) holding a `pp_theme_toggle` for the color mode, swatch rows for the
  Primary/Secondary/Tertiary hues and the Surface tones, and `pp_button`s to
  reset or open the Theme Creator. The swatches are the only custom
  controls: PhoenixPaper has no color-swatch component.

  Every color option is a plain `data-pp-*` attribute on `<html>`
  (`data-pp-primary`, `data-pp-secondary`, `data-pp-tertiary`,
  `data-pp-neutral`), set by small `onclick` strings. The values live in
  `assets/css/theme_picker.css`, generated by `mix site.gen.theme_picker_css`
  from `PhoenixPaper.Theme`, as overrides of the `--color-pp-*` tokens. Each
  row's first swatch is the library's MD3 baseline (no attribute). The
  site's default is the library's whole MD3 baseline scheme (Baseline for every
  role and the surface, so no attributes; `default_attrs/0` renders any
  non-baseline default on `<html>` from root.html.heex), plus System color
  mode; Reset returns to it.

  ## Why `<html>` attributes, not LiveView assigns

  None of this is server state, and `<html>` sits outside every LiveView's
  DOM, so the attributes survive live navigation and LiveView's patching.
  The active swatch's ring is pure CSS, an attribute selector matching
  `<html>`'s current value against each swatch's `data-pp-swatch` marker,
  so there's nothing to keep in sync from JS. The color mode works the same
  way inside `pp_theme_toggle` (it reads `data-theme`).

  ## Persistence

  Only the color mode is saved, by `pp_theme_toggle` under `localStorage`
  `"phx:theme"` (root.html.heex restores it before first paint). The colors
  aren't saved: a hard reload lands back on the site defaults.
  """
  use Phoenix.Component

  use PhoenixPaper.Components

  alias PhoenixPaper.SideSheet

  # Shared by all three color-role rows -- values are the swatch dot's
  # (light-mode) hex, kept in sync with each hue's actual override in
  # assets/css/app.css (including whichever hue is currently a given
  # role's *default*, which needs no override there but still needs a
  # swatch here) so every dot renders as the real current color, not a
  # lookalike.
  @hues [
    {"indigo", "Indigo", "#3f51b5"},
    {"red", "Red", "#dc2626"},
    {"orange", "Orange", "#ea580c"},
    {"amber", "Amber", "#d97706"},
    {"green", "Green", "#16a34a"},
    {"teal", "Teal", "#009688"},
    {"cyan", "Cyan", "#0891b2"},
    {"blue", "Blue", "#2563eb"},
    {"violet", "Violet", "#7c3aed"},
    {"pink", "Pink", "#ff4081"},
    {"rose", "Rose", "#e11d48"},
    {"slate", "Slate", "#475569"}
  ]

  # {data-pp-* attribute, data-pp-swatch group prefix, legend label, default hue}
  # The library's own MD3 baseline is each row's first swatch and the
  # default (no attribute); its dot shows the real baseline color.
  @baseline PhoenixPaperWebsiteWeb.ThemeTokens.defaults().light
  @color_roles [
    {"data-pp-primary", "primary", "Primary", "baseline"},
    {"data-pp-secondary", "secondary", "Secondary", "baseline"},
    {"data-pp-tertiary", "tertiary", "Tertiary", "baseline"}
  ]

  # Swatch dot hex is each tone's `outline` value, not its near-white
  # `surface-variant` -- the surface tones themselves are too close to
  # white/black to tell apart as a small dot, but outline carries each
  # tone's actual hue (slate leans blue, zinc neutral, stone warm) at a
  # lightness that reads clearly in both light and dark panels.
  @neutrals [
    {"baseline", "Baseline", @baseline["surface-variant"]},
    {"slate", "Slate", "#64748b"},
    {"zinc", "Zinc", "#71717a"},
    {"stone", "Stone", "#78716c"}
  ]

  attr(:id, :string, default: "pp-theme-settings")
  attr(:class, :any, default: nil)

  @doc "Renders the theme picker trigger + side sheet. See the module doc."
  def theme_picker(assigns) do
    assigns =
      assigns
      |> assign(:hues, @hues)
      |> assign(:color_roles, @color_roles)
      |> assign(:neutrals, @neutrals)

    ~H"""
    <div id={@id} data-pp-component="theme-picker" class={["inline-block", @class]}>
      <.pp_icon_button
        id={"#{@id}-trigger"}
        icon="hero-swatch"
        label="Theme settings"
        phx-click={SideSheet.show("#{@id}-sheet")}
      />

      <.pp_side_sheet id={"#{@id}-sheet"}>
        <:title>Theme</:title>
        <div class="flex flex-col gap-6">
          <fieldset class="m-0 border-0 p-0">
            <legend class="mb-2.5">
              <.pp_typography variant="label-medium" color="on-surface-variant">
                Color mode
              </.pp_typography>
            </legend>
            <.pp_theme_toggle id={"#{@id}-mode"} />
          </fieldset>

          <fieldset :for={{attr, group, label, default} <- @color_roles} class="m-0 border-0 p-0">
            <legend class="mb-2.5">
              <.pp_typography variant="label-medium" color="on-surface-variant">
                {label}
              </.pp_typography>
            </legend>
            <div class="grid grid-cols-7 gap-2">
              <button
                :for={
                  {value, hue_label, hex} <- [{"baseline", "Baseline", baseline_hex(group)} | @hues]
                }
                type="button"
                data-pp-swatch={"#{group}:#{value}"}
                title={hue_label}
                aria-label={"#{hue_label} #{label} color"}
                onclick={role_apply_js(attr, value, default)}
                style={"background-color: #{hex}"}
                class="size-6 shrink-0 cursor-pointer rounded-pp-full ring-1 ring-inset ring-pp-outline-variant transition-transform hover:scale-110"
              />
            </div>
          </fieldset>

          <fieldset class="m-0 border-0 p-0">
            <legend class="mb-2.5">
              <.pp_typography variant="label-medium" color="on-surface-variant">
                Surface
              </.pp_typography>
            </legend>
            <div class="flex flex-wrap gap-2.5">
              <button
                :for={{value, label, hex} <- @neutrals}
                type="button"
                data-pp-swatch={"neutral:#{value}"}
                title={label}
                aria-label={"#{label} surface tone"}
                onclick={neutral_apply_js(value)}
                style={"background-color: #{hex}"}
                class="size-6 shrink-0 cursor-pointer rounded-pp-full ring-1 ring-inset ring-pp-outline-variant transition-transform hover:scale-110"
              />
            </div>
          </fieldset>
        </div>

        <:actions>
          <.pp_button id="create-theme-link" variant="tonal" navigate="/theme-creator">
            <:start_icon><.pp_icon name="hero-sparkles" size="sm" /></:start_icon>
            Create your theme
          </.pp_button>
          <.pp_button id={"#{@id}-reset"} variant="text" onclick={reset_js()}>
            Reset
          </.pp_button>
        </:actions>
      </.pp_side_sheet>
    </div>
    """
  end

  # Saved under "phx:theme", the same key PhoenixPaper.ThemeToggle uses and
  # root.html.heex restores, so the picker and every toggle agree and the
  # choice survives a reload. System removes it.
  defp mode_apply_js("system"),
    do:
      "document.documentElement.removeAttribute('data-theme');" <>
        "localStorage.removeItem('phx:theme');"

  defp mode_apply_js(value),
    do:
      "document.documentElement.setAttribute('data-theme',#{inspect(value)});" <>
        "localStorage.setItem('phx:theme',#{inspect(value)});"

  defp baseline_hex(group), do: @baseline[group]

  # Baseline is "no attribute"; any hue (including a role's site default,
  # which root.html.heex renders as an attribute) is set explicitly.
  defp role_apply_js(attr, "baseline", _default),
    do: "document.documentElement.removeAttribute(#{inspect(attr)});"

  defp role_apply_js(attr, value, _default),
    do: "document.documentElement.setAttribute(#{inspect(attr)},#{inspect(value)});"

  defp neutral_apply_js("baseline"),
    do: "document.documentElement.removeAttribute('data-pp-neutral');"

  defp neutral_apply_js(value),
    do: "document.documentElement.setAttribute('data-pp-neutral',#{inspect(value)});"

  # Back to the site defaults: each role's default (see @color_roles, and
  # the matching attributes in root.html.heex), baseline surface, System mode.
  defp reset_js do
    mode_apply_js("system") <>
      Enum.map_join(@color_roles, "", fn {attr, _group, _label, default} ->
        role_apply_js(attr, default, default)
      end) <>
      neutral_apply_js("baseline")
  end

  @doc "The `<html>` attributes for the site's default role hues (used by root.html.heex)."
  def default_attrs do
    for {attr, _group, _label, default} <- @color_roles, default != "baseline", into: %{} do
      {attr, default}
    end
  end

  @doc "The role hues, `{value, label, hex}` (also used by ThemePickerCss)."
  def hues, do: @hues

  @doc "The surface tones, `{value, label, hex}`, baseline first."
  def neutrals, do: @neutrals
end
