defmodule PhoenixPaperWebsiteWeb.ThemePickerCss do
  @moduledoc """
  Builds `assets/css/theme_picker.css`, the CSS behind
  `PhoenixPaperWebsiteWeb.ThemePicker`'s swatches (regenerate it with
  `mix site.gen.theme_picker_css`).

  Every color comes from phoenix_paper's own MD3 color science
  (`PhoenixPaper.Theme`), so a picked hue is a proper tonal set:

    * a Primary/Secondary/Tertiary hue is a `:fidelity` scheme seeded with
      that hue (fidelity keeps the hue's own chroma, so "red" stays vivid),
      whose primary roles (role, on-role, container, on-container) are
      written to the picked role's tokens, light and dark;
    * a Surface tone is a `:neutral` scheme's whole surface family.

  No attribute is the library's MD3 baseline (the site default).
  """

  alias PhoenixPaperWebsiteWeb.ThemePicker

  @roles ~w(primary secondary tertiary)
  @surface ~w(surface surface-dim surface-bright surface-container-lowest surface-container-low surface-container surface-container-high surface-container-highest surface-variant on-surface on-surface-variant outline outline-variant inverse-surface inverse-on-surface)

  def css do
    {role_rules, role_fallback} = role_rules()
    {surface_rules, surface_fallback} = surface_rules()

    [
      header(),
      role_rules,
      surface_rules,
      "/* System dark (no explicit data-theme yet) */\n@media (prefers-color-scheme: dark) {\n" <>
        Enum.join(role_fallback ++ surface_fallback, "\n") <> "\n}",
      rings()
    ]
    |> Enum.join("\n\n")
    |> Kernel.<>("\n")
  end

  defp role_rules do
    rules =
      for role <- @roles, {name, _label, hex} <- ThemePicker.hues() do
        light = PhoenixPaper.Theme.scheme(hex, :light, variant: :fidelity)
        dark = PhoenixPaper.Theme.scheme(hex, :dark, variant: :fidelity)
        sel = ~s([data-pp-#{role}="#{name}"])

        {"#{sel} { #{role_decl(role, light)} }\n#{sel}[data-theme=\"dark\"] { #{role_decl(role, dark)} }",
         ~s(  #{sel}:not([data-theme="light"]\) { #{role_decl(role, dark)} })}
      end

    {"/* Primary / Secondary / Tertiary */\n" <> Enum.map_join(rules, "\n", &elem(&1, 0)),
     Enum.map(rules, &elem(&1, 1))}
  end

  # The seed's primary tonal roles, written to `role`'s tokens.
  defp role_decl(role, scheme) do
    [{"", ""}, {"on-", ""}, {"", "-container"}, {"on-", "-container"}]
    |> Enum.map_join(" ", fn {pre, suf} ->
      "--color-pp-#{pre}#{role}#{suf}: #{scheme["#{pre}primary#{suf}"]};"
    end)
  end

  defp surface_rules do
    rules =
      for {name, _label, hex} <- ThemePicker.neutrals(), name != "baseline" do
        light = PhoenixPaper.Theme.scheme(hex, :light, variant: :neutral)
        dark = PhoenixPaper.Theme.scheme(hex, :dark, variant: :neutral)
        sel = ~s([data-pp-neutral="#{name}"])

        {"#{sel} { #{surface_decl(light)} }\n#{sel}[data-theme=\"dark\"] { #{surface_decl(dark)} }",
         ~s(  #{sel}:not([data-theme="light"]\) { #{surface_decl(dark)} })}
      end

    {"/* Surface tones */\n" <> Enum.map_join(rules, "\n", &elem(&1, 0)),
     Enum.map(rules, &elem(&1, 1))}
  end

  defp surface_decl(scheme), do: Enum.map_join(@surface, " ", &"--color-pp-#{&1}: #{scheme[&1]};")

  defp rings do
    role_rings =
      for role <- @roles do
        [
          ~s(  html:not([data-pp-#{role}]\) [data-pp-swatch="#{role}:baseline"])
          | for(
              {name, _, _} <- ThemePicker.hues(),
              do: ~s(  html[data-pp-#{role}="#{name}"] [data-pp-swatch="#{role}:#{name}"])
            )
        ]
      end

    surface_rings =
      for {name, _, _} <- ThemePicker.neutrals() do
        if name == "baseline",
          do: ~s(  html:not([data-pp-neutral]\) [data-pp-swatch="neutral:baseline"]),
          else: ~s(  html[data-pp-neutral="#{name}"] [data-pp-swatch="neutral:#{name}"])
      end

    """
    /* The active swatch in each group gets a ring, derived purely from <html>'s
       data-pp-* attributes, so there's no JS state to keep in sync. */
    :is(
    #{Enum.join(List.flatten(role_rings) ++ surface_rings, ",\n")}
    ) {
      box-shadow: 0 0 0 2px var(--color-pp-surface), 0 0 0 4px var(--color-pp-on-surface);
      transform: scale(1.1);
    }\
    """
  end

  defp header do
    """
    /*
     * GENERATED by `mix site.gen.theme_picker_css` from
     * PhoenixPaperWebsiteWeb.ThemePickerCss -- don't edit by hand.
     *
     * The theme picker's Primary/Secondary/Tertiary hues and Surface tones,
     * as overrides of phoenix_paper's --color-pp-* tokens, every value from
     * PhoenixPaper.Theme (MD3 color science). Per rule: a light selector, an
     * explicit-dark one, and the same dark values for System users at the end.
     */\
    """
  end
end
